dist: trusty
language: node_js
install:
- wget -qO- https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz | tar xvz
- wget -qO- https://cmake.org/files/v3.9/cmake-3.9.0-rc2-Linux-x86_64.tar.gz | tar xvz && ln -s cmake-3.9.0-rc2-Linux-x86_64 cmake
- export PATH=$(pwd)/cmake/bin:$PATH
- ./emsdk-portable/emsdk install sdk-incoming-64bit
script:
- ./emsdk-portable/emsdk activate sdk-incoming-64bit
- ./binaryen/build-js.sh && cp ./binaryen/bin/binaryen.js ./index.js
# TODO: update version and publish to npm
